### PR TITLE
"use strict" and other linty fixes

### LINKED ISSUE #1670: mithril.js should have "use strict"
Nothing like a bunch of grief over finding out changes to parameters are being unexpectedly mirrored in `arguments` within a function. ☹️

### PR DESCRIPTION
**Pull request by isiahmeadows**
~~**Note: DO NOT MERGE UNTIL [THIS ISSUE](https://github.com/lhorie/mithril.js/pull/1652#issuecomment-283747176) IS RESOLVED.**~~

~~That will likely generate merge conflicts that I'll need to resolve on my end.~~

Fixed in #1674.

---

Fixes #1670 

- I set `"strict"` to `["error", "global"]` for everywhere, and fixed everything accordingly.
- I also changed `.eslintignore` to ignore far fewer files, and fixed them accordingly.
- I edited the `.gitignore` to include `.eslintcache` (a file generated locally by ESLint).

### CODE REVIEW

**Comment by isiahmeadows** [comment]
Note: this is blocked on [this issue](https://github.com/lhorie/mithril.js/pull/1652#issuecomment-283747176) being resolved.

**Comment by tivac** [comment]
I strongly dislike the changing of template literals to double-quoted strings with escaping. It adds a lot of visual noise.

I understand why we don't want template literals in the main library but there's nothing wrong with them in the tests. Issues like that are presumably why test files were excluded from being linted previously.

**Comment by isiahmeadows** [comment]
@tivac I can edit that rule. I just used ESLint's auto-fixing tool rather blindly. Since I changed so many files, could you leave a comment on the relevant lines so I know where to look?

**Comment by isiahmeadows** [comment]
Oh, and some of the tests had undeclared variables absorbed by try-catch blocks.

File: stream/tests/test-stream.js [hunk 1]
```diff
@@ -210,8 +208,9 @@ o.spec("stream", function() {
 			var a = Stream()
 			var b = Stream()
 
-			var all = Stream.merge([a.map(id), b.map(id)]).map(function(data) {
+			Stream.merge([a.map(id), b.map(id)]).map(function(data) {
 				value = data[0] + data[1]
+				return undefined
```
Comment (pygy) [inline stream/tests/test-stream.js]: This one is surprising... What linter rule mandates this?

**Comment by pygy** [comment]
https://github.com/lhorie/mithril.js/pull/1671/files#diff-65a9ca1b5b773a0aa6697735a249f6f7

You can fix it by using single quotes inside, for example, or by allowing single quoted strings when it avoids escapes (there's an option in ESLint for the latter IIRC).

File: test-utils/domMock.js [hunk 2]
```diff
@@ -297,17 +300,18 @@ module.exports = function() {
 						element.firstChild != null ? element.firstChild.nodeValue : ""
 				}
 				if (element.nodeName === "SELECT") {
-					var selectedValue, selectedIndex = 0
+					// var selectedValue
```
Comment (lhorie) [inline test-utils/domMock.js]: why is this commented out now?

File: test-utils/tests/test-pushStateMock.js [hunk 3]
```diff
@@ -167,14 +167,14 @@ o.spec("pushStateMock", function() {
...
 	o.spec("set protocol", function() {
-		o("setting protocol throws", function(done) {
-			var old = $window.location.href
+		o("setting protocol throws", function() {
 			try {
 				$window.location.protocol = "https://"
 			}
 			catch (e) {
-				done()
+				return
```
Comment (lhorie) [inline test-utils/tests/test-pushStateMock.js]: done() asserts and thus counts towards the total test count, simply returning does not

File: test-utils/xhrMock.js [hunk 4]
```diff
@@ -6,7 +6,7 @@ var parseQueryString = require("../querystring/parse")
 
 module.exports = function() {
 	var routes = {}
-	var callback = "callback"
+	// var callback = "callback"
```
Comment (lhorie) [inline test-utils/xhrMock.js]: why is this commented out?

File: test-utils/xhrMock.js [hunk 5]
```diff
@@ -83,8 +82,8 @@ module.exports = function() {
 		$defineRoutes: function(rules) {
 			routes = rules
 		},
-		$defineJSONPCallbackKey: function(key) {
-			callback = key
+		$defineJSONPCallbackKey: function(/* key */) {
```
Comment (lhorie) [inline test-utils/xhrMock.js]: why is this commented out?

Comment (FibreFoX) [inline test-utils/xhrMock.js]: I assume because `callback` never gets called, which might be reported by ESLint, but @isiahmeadows missed to remove it ;)

File: stream/tests/test-stream.js (hunk 1 above)
Comment (isiahmeadows) [inline stream/tests/test-stream.js]: [`array-callback-return`](http://eslint.org/docs/rules/array-callback-return), which doesn't understand types.

File: test-utils/tests/test-pushStateMock.js (hunk 3 above)
Comment (isiahmeadows) [inline test-utils/tests/test-pushStateMock.js]: I'll fix it to `return done()`.

File: test-utils/xhrMock.js (hunk 4 above)
Comment (isiahmeadows) [inline test-utils/xhrMock.js]: Wasn't used, and wasn't sure if it were required.

File: test-utils/xhrMock.js (hunk 5 above)
Comment (isiahmeadows) [inline test-utils/xhrMock.js]: It's commented out because the key wasn't used for anything. I feel it might be a programming error, though, thus it being commented out. (It's set in the parent scope to `"callback"`.)

File: test-utils/domMock.js (hunk 2 above)
Comment (isiahmeadows) [inline test-utils/domMock.js]: Unused, but I didn't think removing it was safe.

**Comment by isiahmeadows** [comment]
By the way, the template literal issue was because the [`"avoid-escape"` positional value for `"quotes"`](http://eslint.org/docs/rules/quotes) is deprecated, with support removed. I'm reverting all the relevant changes to that.

File: stream/tests/test-stream.js (hunk 1 above)
Comment (isiahmeadows) [inline stream/tests/test-stream.js]: The alternative is just disabling the rule, but this was less verbose.

File: test-utils/tests/test-pushStateMock.js (hunk 3 above)
Comment (isiahmeadows) [inline test-utils/tests/test-pushStateMock.js]: Wonder if `o.throws(func)` should be added to ospec? I see patterns like this enough in the tests that I feel such an addition could be merited.

**Comment by pygy** [comment]
@isiahmeadows While I welcome a seasonal cleanup, I wouldn't want to have the linter breathing down my neck when I write tests/debug Mithril...

**Comment by isiahmeadows** [comment]
@lhorie The reasons I commented out a lot of code is because in many cases, it clearly implemented some sort of functionality, but nothing was actually being done. I felt leaving the code commented out was better than just removing it, so if someone decided to finish implementing it, they'd at least have somewhere to start.

File: .gitignore [hunk 6]
```diff
@@ -4,3 +4,4 @@ jsconfig.json
 npm-debug.log
 .vscode
 .DS_Store
+.eslintcache
```
Comment (isiahmeadows) [inline .gitignore]: This is to allow people to use `eslint --cache`, which doesn't lint unchanged files.

**Comment by isiahmeadows** [comment]
@pygy FWIW, I personally find it easier to avoid buggy code when the linter is strict, since you can avoid numerous errors without even running a single test (similar benefits to static typing). Also, until this patch, the tests would've had syntax errors in IE 9 (our baseline). I only modified two rules (enable strict mode and migrate a deprecated attribute), but the only other major thing I did was enable the linter in most places. If you look at the [diff](https://github.com/lhorie/mithril.js/pull/1671/files#diff-1b0fd5322de42e11c8786543f74c7c41), you'll notice a few other issues:

- It was ignoring directories that didn't exist (`archive` and `coverage`).
- It was erroneously ignoring potential subdirectories (hence the new preceding `/` throughout).
- It was ignoring all of ospec and the bundler.
- It was ignoring the docs build scripts.
- It was ignoring the complex test mocks (if those break, the tests themselves could break).

But enabling it for the tests, too, it does two things:

1. Better ensures people adhere to the existing style.
2. Ensures there are fewer obvious errors in the tests leading to false positives. (An unused variable could easily be an unchecked value.)

**Comment by isiahmeadows** [comment]
Pushed some fixes for the quote escape issues.

**Comment by pygy** [comment]
@isiahmeadows `coverage` is created if you run `npm run cover`. I suppose I can `npm-run ospec` rather than `npm run test`...

**Comment by isiahmeadows** [comment]
@pygy I missed that. Will fix.

**Comment by lhorie** [comment]
ugh there's some conflicts now

**Comment by isiahmeadows** [comment]
@lhorie I expected conflicts would periodically arise, and directed #1682 to go through despite it causing some conflicts.

**Comment by isiahmeadows** [comment]
Nothing to worry about here.
